Better control of the result of dig, to avoid the "delete all TLDs" bug
git-svn-id: https://svn.generic-nic.net/NIC-generique/iana/whois@10763 e62f009e-d044-43ae-9900-873abb462db7

diff --git a/get-whois-and-commit b/get-whois-and-commit
--- a/get-whois-and-commit
+++ b/get-whois-and-commit
@@ -20,9 +20,19 @@ if [ ! -e $LIST ]; then
     sendemail.py -t $MAINTAINER -f $MAINTAINER -s "Cannot find $LIST" < /dev/null
 fi
 
-dig @${ROOTNAMESERVER}.root-servers.net AXFR . | awk -F. '/^[A-Za-z][A-Za-z0-9-]+\.\t.*NS/ {print toupper($1)}' | sort | uniq > $TLDFILE
+(dig @${ROOTNAMESERVER}.root-servers.net AXFR . | awk -F. '/^[A-Za-z][A-Za-z0-9-]+\.\t.*NS/ {print toupper($1)}' | sort | uniq > $TLDFILE) 2> $LOG
+# dig does not set a proper return code
+
+if [ ! -z "$(cat $LOG)" ]; then
+    sendemail.py -t $MAINTAINER -f $MAINTAINER -s "Cannot retrieve the list of TLDs" < $LOG
+    exit 1
+fi
 
 TLDS=$(cat $TLDFILE)
+if [ -z "$TLDS" ]; then
+    sendemail.py -t $MAINTAINER -f $MAINTAINER -s "List of TLDs is empty" < $LOG
+    exit 1
+fi
 
 svn update -q
 
